Update input.cc
kitao/pyxel pull request #295
Opened 2020-12-20 05:45 UTC by Aayush-Bachwana-25

Indented input.cc

2021-03-07 08:50 UTC, MichaelCurrin commented on pyxel/core/src/pyxelcore/input.cc
> +{
It is not reasonable to change the indentation style to start `{` on a newline by itself.

It adds extra lines without an increase in readability (I think), it is inconsistent with the rest of the project and is an uncommon style (I _very_ rarely see it across any language PHP, C, JS, Go, Rust).

See also Google's C++ style guide https://google.github.io/styleguide/cppguide.html#Namespaces

```cc
// In the .cc file
namespace mynamespace {

void MyClass::Foo() {
}
}  
```

2021-03-07 08:52 UTC, MichaelCurrin commented on pyxel/core/src/pyxelcore/input.cc
> +  mouse_x_ = (mouse_x_ - (window->WindowX() + window->ScreenX())) / window->ScreenScale();
I think the formula was deliberately setup as two lines so make it clear what is on the top and what is on the bottom. Now this is less clear.

2021-03-07 08:53 UTC, MichaelCurrin commented on pyxel/core/src/pyxelcore/input.cc
> +    SDL_SetCursor(mouse_x_ >= 0 && mouse_x_ < window->ScreenWidth() && mouse_y_ >= 0 && mouse_y_ < window->ScreenHeight()  ?  blank_cursor_ : normal_cursor_);
This is way too long. On a typical laptop screen mine, this cuts off after `?`.

It's also a lot of more mental effort to read a super long line that one that is broken up into small pieces on 4 lines.

2021-03-07 08:54 UTC, MichaelCurrin requested changes
Most of the changes in this PR are not appropriate as they change the style too aggressively, at the cost of readability.

2021-05-23 08:06 UTC, kitao commented
I am mechanically adapting clang-format to the code. That is Pyxel's C ++ format policy.

2021-05-23 08:06 UTC, closed without merging